"""Add payment user_id and payment_type

Revision ID: db15c38a4c1e
Revises: 
Create Date: 2026-07-02 16:47:08.166775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db15c38a4c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('main_wallet', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('task_wallet', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('team_wallet', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('withdrawn', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vip_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('joined_at')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('vip_level')
        batch_op.drop_column('withdrawn')
        batch_op.drop_column('team_wallet')
        batch_op.drop_column('task_wallet')
        batch_op.drop_column('main_wallet')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_code')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
