"""Add VIP fields to User

Revision ID: ffdf02b30ee0
Revises: 23ca01f400fd
Create Date: 2026-07-04 23:56:34.889532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffdf02b30ee0'
down_revision = '23ca01f400fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_task_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vip_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vip_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('vip_expires_at')
        batch_op.drop_column('vip_started_at')
        batch_op.drop_column('last_task_date')
        batch_op.drop_column('tasks_completed')

    # ### end Alembic commands ###
